# Generated by Django 4.2.2 on 2023-07-02 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("school", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="imageinsert",
            name="address",
            field=models.CharField(max_length=200, null=True),
        ),
    ]
