# Generated by Django 4.2.1 on 2023-05-21 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0014_frenchiseextra_city_frenchiseextra_district_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentextra',
            name='cl',
            field=models.CharField(choices=[('one', 'course1'), ('two', 'course2'), ('three', 'course3'), ('four', 'course4'), ('five', 'course5'), ('six', 'course6'), ('seven', 'course7'), ('eight', 'course8'), ('nine', 'course9'), ('ten', 'course10')], default='one', max_length=10),
        ),
    ]
