# Generated by Django 4.2.1 on 2023-05-22 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0015_alter_studentextra_cl'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacherextra',
            name='aadhar',
            field=models.FileField(null=True, upload_to='static/teacher_aadhar'),
        ),
        migrations.AddField(
            model_name='teacherextra',
            name='course',
            field=models.CharField(choices=[('one', 'course1'), ('two', 'course2'), ('three', 'course3'), ('four', 'course4'), ('five', 'course5'), ('six', 'course6'), ('seven', 'course7'), ('eight', 'course8'), ('nine', 'course9'), ('ten', 'course10')], default='one', max_length=10),
        ),
        migrations.AddField(
            model_name='teacherextra',
            name='degree',
            field=models.FileField(null=True, upload_to='static/teacher_degree'),
        ),
        migrations.AddField(
            model_name='teacherextra',
            name='district',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='teacherextra',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='teacherextra',
            name='g_choices',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Others')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='teacherextra',
            name='permanent_address',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='teacherextra',
            name='photo',
            field=models.ImageField(null=True, upload_to='static/teacher_photos'),
        ),
        migrations.AddField(
            model_name='teacherextra',
            name='pin_code',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='teacherextra',
            name='present_address',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='teacherextra',
            name='resume',
            field=models.FileField(null=True, upload_to='static/teacher_resume'),
        ),
        migrations.AddField(
            model_name='teacherextra',
            name='state',
            field=models.CharField(choices=[('andaman_nicobar_island', 'Andaman and Nicobar Island'), ('andhra_pradesh', 'Andhra Pradesh'), ('arunachal_pradesh', 'Arunachal Pradesh'), ('assam', 'Assam'), ('bihar', 'Bihar'), ('chandigarh', 'Chandigarh'), ('chhattisgarh', 'Chhattisgarh'), ('dadra_nagar_haveli', 'Dadra and Nagar Haveli'), ('daman_diu', 'Daman and Diu'), ('delhi', 'Delhi'), ('goa', 'Goa'), ('gujarat', 'Gujarat'), ('haryana', 'Haryana'), ('himachal_pradesh', 'Himachal Pradesh'), ('jammu_kashmir', 'Jammu and Kashmir'), ('jharkhand', 'Jharkhand'), ('karnataka', 'Karnataka'), ('kerala', 'Kerala'), ('lakshadweep', 'Lakshadweep'), ('madhya_pradesh', 'Madhya Pradesh'), ('maharashtra', 'Maharashtra'), ('manipur', 'Manipur'), ('meghalaya', 'Meghalaya'), ('mizoram', 'Mizoram'), ('nagaland', 'Nagaland'), ('odisha', 'Odisha'), ('puducherry', 'Puducherry'), ('punjab', 'Punjab'), ('rajasthan', 'Rajasthan'), ('sikkim', 'Sikkim'), ('tamil_nadu', 'Tamil Nadu'), ('telangana', 'Telangana'), ('tripura', 'Tripura'), ('uttar_pradesh', 'Uttar Pradesh'), ('uttarakhand', 'Uttarakhand'), ('west_bengal', 'West Bengal')], max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='studentextra',
            name='date_of_birth',
            field=models.DateField(),
        ),
    ]
