# Generated by Django 4.2.1 on 2023-05-22 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0016_teacherextra_aadhar_teacherextra_course_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(max_length=100, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('status', models.CharField(default='created', max_length=20)),
            ],
        ),
        migrations.RemoveField(
            model_name='frenchiseextra',
            name='payment_id',
        ),
    ]
