# Generated by Django 4.2.1 on 2023-05-23 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0017_order_remove_frenchiseextra_payment_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='frenchiseextra',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
