# Generated by Django 4.2.2 on 2023-07-01 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0018_frenchiseextra_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='imageinsert',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='static/images/')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='Attendance',
        ),
        migrations.RemoveField(
            model_name='frenchiseextra',
            name='user',
        ),
        migrations.DeleteModel(
            name='Notice',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.RemoveField(
            model_name='studentextra',
            name='user',
        ),
        migrations.RemoveField(
            model_name='teacherextra',
            name='user',
        ),
        migrations.DeleteModel(
            name='FrenchiseExtra',
        ),
        migrations.DeleteModel(
            name='StudentExtra',
        ),
        migrations.DeleteModel(
            name='TeacherExtra',
        ),
    ]
